baseurl = "https://clcert.cl"
author = "CLCERT Universidad de Chile"
title = "Laboratorio de Criptografía Aplicada y Ciberseguridad - CLCERT"
languageCode = "es-cl"
theme = "clcert-lab"
enableRobotsTXT = true
mainSections = ["blog"]
SectionPagesMenu = ["main", "social"]

[params]
# Files in assets
css = [
    "css/foundation.css",
    "scss/styles.scss",
    "css/font-awesome.min.css",
]
js = [
    "js/jquery.js",
    "js/what-input.js",
    "js/foundation.js",
    "js/app.js",
]



[params.meta]
description = "Tema oficial CLCERT, basado en Go Foundation"
keywords = "clcert, uchile"

[params.hero]
herodescription = '''
Somos un grupo de académicos, profesionales y estudiantes dedicados a generar conocimiento especializado y herramientas en criptografía aplicada y ciberseguridad. Buscamos entender los sistemas informáticos que nos rodean para identificar y resolver sus problemas de seguridad.
'''
link = "/laboratorio"

[[menu.main]]
name = "Laboratorio"
weight = 1
url = "/laboratorio"

[[menu.main]]
name = "Integrantes"
weight = 2
url = "/integrantes"

[[menu.main]]
name = "Proyectos"
weight = 3
url = "/proyectos"

[[menu.main]]
name = "Blog"
weight = 4
url = "/blog"

[[menu.main]]
name = "Humor"
weight = 6
url = "/humor"

[[menu.main]]
name = "Contacto"
weight = 7
url = "/contacto"

[[menu.footer]]
name = "Preguntas Frecuentes"
url = "/faq"
weight = 1

[[menu.footer]]
name = "Políticas de Confidencialidad"
url = "/confidencialidad"
weight = 2

[[menu.footer]]
name = "Cómo citarnos"
url = "/citas"
weight = 3 


[[menu.footer]]
name = "Twitter"
url = "http://twitter.com/clcert"
weight = 4

[[menu.footer]]
name = "Github"
url = "http://github.com/clcert"
weight = 5

[[menu.footer]]
name = "Instagram"
url = "https://www.instagram.com/clcert.cl/"
weight = 6

